/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hashing;


import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mithun
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
        this.setSize(1280,770);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        s4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        s2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        s6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        s7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        s3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        s5 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(12, 11, 11));
        jPanel2.setLayout(null);

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("SEARCH");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(690, 60, 120, 40);

        s4.setBackground(new java.awt.Color(51, 51, 51));
        s4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        s4.setForeground(new java.awt.Color(255, 255, 255));
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        jPanel2.add(s4);
        s4.setBounds(470, 67, 190, 33);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("UID -");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(380, 60, 70, 40);

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 255));
        jLabel13.setText("UID -");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(50, 160, 80, 40);

        s1.setBackground(new java.awt.Color(51, 51, 51));
        s1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        s1.setForeground(new java.awt.Color(255, 255, 255));
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        jPanel2.add(s1);
        s1.setBounds(210, 170, 230, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 255));
        jLabel9.setText("USER NAME -");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(50, 250, 140, 30);

        s2.setBackground(new java.awt.Color(51, 51, 51));
        s2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        s2.setForeground(new java.awt.Color(255, 255, 255));
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        jPanel2.add(s2);
        s2.setBounds(210, 250, 230, 35);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("CHECK-IN -");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(620, 200, 120, 30);

        s6.setBackground(new java.awt.Color(51, 51, 51));
        s6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        s6.setForeground(new java.awt.Color(255, 255, 255));
        s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6ActionPerformed(evt);
            }
        });
        jPanel2.add(s6);
        s6.setBounds(810, 200, 230, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 255));
        jLabel14.setText("CHECK-OUT -");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(620, 300, 160, 30);

        s7.setBackground(new java.awt.Color(51, 51, 51));
        s7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        s7.setForeground(new java.awt.Color(255, 255, 255));
        s7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s7ActionPerformed(evt);
            }
        });
        jPanel2.add(s7);
        s7.setBounds(810, 300, 230, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("PURPOSE -");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(50, 340, 120, 30);

        s3.setBackground(new java.awt.Color(51, 51, 51));
        s3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        s3.setForeground(new java.awt.Color(255, 255, 255));
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        jPanel2.add(s3);
        s3.setBounds(210, 340, 230, 35);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("SYSTEM ID -");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 410, 130, 30);

        s5.setBackground(new java.awt.Color(51, 51, 51));
        s5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        s5.setForeground(new java.awt.Color(255, 255, 255));
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });
        jPanel2.add(s5);
        s5.setBounds(210, 415, 230, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(530, 160, 10, 290);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 120, 1130, 560);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("LOGOUT");
        jLabel6.setToolTipText("");
        jLabel6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel6FocusGained(evt);
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 0, 90, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(1010, 80, 100, 30);

        jLabel7.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SEARCH INFO");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 10, 130, 20);

        jLabel12.setFont(new java.awt.Font("Product Sans", 1, 21)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("CYBER CAFE RECORD SYSTEM");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(420, 10, 330, 28);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(null);

        jLabel8.setBackground(new java.awt.Color(204, 255, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("<-- HOME");
        jLabel8.setToolTipText("");
        jLabel8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel8FocusGained(evt);
            }
        });
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel8);
        jLabel8.setBounds(10, 0, 80, 30);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(20, 80, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1130, 120);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        
    }//GEN-LAST:event_s4ActionPerformed

    private void s7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s7ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s2ActionPerformed

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                Hashing.search();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6FocusGained

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.dispose();
        Login.main(new String[]{});
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        Adddet ad=new Adddet();
        ad.setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel8FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8FocusGained

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
        Selpage.main(new String[]{});
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        this.dispose();
        Selpage.main(new String[]{});
    }//GEN-LAST:event_jPanel6MouseClicked

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s3ActionPerformed

    private void s6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField s1;
    public static javax.swing.JTextField s2;
    public static javax.swing.JTextField s3;
    public static javax.swing.JTextField s4;
    public static javax.swing.JTextField s5;
    public static javax.swing.JTextField s6;
    public static javax.swing.JTextField s7;
    // End of variables declaration//GEN-END:variables
}
